# Generated by Django 2.1.5 on 2019-03-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arti_title', models.CharField(max_length=125)),
                ('arti_author', models.CharField(max_length=50)),
                ('arti_content', models.TextField()),
                ('arti_createtime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=20)),
                ('game_url', models.CharField(max_length=32)),
                ('game_company', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_title', models.CharField(max_length=125)),
                ('pic_context', models.CharField(max_length=255)),
                ('pic_url', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=125)),
                ('user_pwd', models.CharField(max_length=135)),
                ('user_email', models.CharField(max_length=120)),
                ('user_sex', models.CharField(max_length=5)),
            ],
        ),
    ]
